sudo: required
services:
  - docker

before_install:
  - docker build -t inazrabuu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true inazrabuu/react-test yarn test 

after_success:
  - docker build -t inazrabuu/multi-client ./client
  - docker build -t inazrabuu/multi-nginx ./nginx
  - docker build -t inazrabuu/multi-server ./server
  - docker build -t inazrabuu/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push inazrabuu/multi-client
  - docker push inazrabuu/multi-nginx
  - docker push inazrabuu/multi-server
  - docker push inazrabuu/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: fs-app-prod-1
  env: Fsappprod1-env
  bucket_name: elasticbeanstalk-ap-southeast-1-887785090245
  bucket_path: fs-app-prod-1
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
